-- Seed script: Insert existing lead vendors with DIDs
-- Run this after creating the lead_vendors table

INSERT INTO public.lead_vendors (name, did, is_active) VALUES
    ('Ark Tech', NULL, true),
    ('GrowthOnics BPO', NULL, true),
    ('Maverick', NULL, true),
    ('Omnitalk BPO', NULL, true),
    ('Vize BPO', NULL, true),
    ('Corebiz', 'Contact Corebiz', true),
    ('Digicon', NULL, true),
    ('Ambition', '8036808613', true),
    ('Benchmark', NULL, true),
    ('Poshenee', NULL, true),
    ('Plexi', NULL, true),
    ('Gigabite', NULL, true),
    ('Everline solution', NULL, true),
    ('Progressive BPO', NULL, true),
    ('Cerberus BPO', NULL, true),
    ('NanoTech', '4696296367', true),
    ('Optimum BPO', NULL, true),
    ('Ethos BPO', NULL, true),
    ('Trust Link', NULL, true),
    ('Crown Connect BPO', 'Contact Crown Connect BPO', true),
    ('Quotes BPO', NULL, true),
    ('Zupax Marketing', 'Contact Zupax Marketing', true),
    ('Argon Comm', 'Contact Argon Comm', true),
    ('Care Solutions', NULL, true),
    ('Cutting Edge', NULL, true),
    ('Next Era', NULL, true),
    ('Rock BPO', '9182486011', true),
    ('Avenue Consultancy', '3465896057', true),
    ('AJ BPO', 'Contact AJ BPO', true),
    ('Lavish BPO', NULL, true),
    ('Pro Solutions BPO', NULL, true),
    ('Emperor BPO', NULL, true),
    ('Networkize', NULL, true),
    ('LightVerse BPO', NULL, true),
    ('Leads BPO', 'Contact Leads BPO', true),
    ('Helix BPO', NULL, true),
    ('CrossNotch', '9298101908', true),
    ('StratiX BPO', '7273545717', true),
    ('Exito BPO', 'Contact Exito BPO', true),
    ('Lumenix BPO', NULL, true),
    ('All-Star BPO', NULL, true),
    ('DownTown BPO', 'Contact DownTown BPO', true),
    ('TechPlanet', '+1 (833) 817-1810', true),
    ('Livik BPO', NULL, true),
    ('NexGen BPO', NULL, true),
    ('Quoted-Leads BPO', '12179961427', true),
    ('SellerZ BPO', '9086641503', true),
    ('Venom BPO', NULL, true),
    ('Core Marketing', NULL, true),
    ('WinBPO', '+12163009420', true),
    ('Everest BPO', NULL, true),
    ('Riztech BPO', NULL, true),
    ('Broker Leads BPO', NULL, true),
    ('Alternative BPO', NULL, true),
    ('Unified Systems BPO', NULL, true),
    ('Hexa Affiliates', NULL, true)
ON CONFLICT (name) DO UPDATE 
SET did = EXCLUDED.did,
    is_active = true,
    updated_at = timezone('utc'::text, now());
